#ifndef OJAX_PJRT_ABI_ASSERT_H_
#define OJAX_PJRT_ABI_ASSERT_H_
#include <stddef.h>
#include "pjrt_c_api.h"
_Static_assert(PJRT_API_MAJOR == 0, "PJRT_API_MAJOR drift");
_Static_assert(PJRT_API_MINOR == 81, "PJRT_API_MINOR drift");
_Static_assert(sizeof(PJRT_Api) == 984, "PJRT_Api size drift");
_Static_assert(sizeof(PJRT_Api_Version) == 24, "PJRT_Api_Version size drift");
_Static_assert(offsetof(PJRT_Api, struct_size) == 0, "PJRT_Api.struct_size offset drift");
_Static_assert(offsetof(PJRT_Api, extension_start) == 8, "PJRT_Api.extension_start offset drift");
_Static_assert(offsetof(PJRT_Api, pjrt_api_version) == 16, "PJRT_Api.pjrt_api_version offset drift");
_Static_assert(offsetof(PJRT_Api_Version, struct_size) == 0, "PJRT_Api_Version.struct_size offset drift");
_Static_assert(offsetof(PJRT_Api_Version, extension_start) == 8, "PJRT_Api_Version.extension_start offset drift");
_Static_assert(offsetof(PJRT_Api_Version, major_version) == 16, "PJRT_Api_Version.major_version offset drift");
_Static_assert(offsetof(PJRT_Api_Version, minor_version) == 20, "PJRT_Api_Version.minor_version offset drift");
_Static_assert(offsetof(PJRT_Api, PJRT_Error_Destroy) == 40, "PJRT_Api.PJRT_Error_Destroy offset drift");
_Static_assert(offsetof(PJRT_Api, PJRT_Error_Message) == 48, "PJRT_Api.PJRT_Error_Message offset drift");
_Static_assert(offsetof(PJRT_Api, PJRT_Error_GetCode) == 56, "PJRT_Api.PJRT_Error_GetCode offset drift");
_Static_assert(offsetof(PJRT_Api, PJRT_Plugin_Initialize) == 64, "PJRT_Api.PJRT_Plugin_Initialize offset drift");
_Static_assert(offsetof(PJRT_Api, PJRT_Plugin_Attributes) == 72, "PJRT_Api.PJRT_Plugin_Attributes offset drift");
_Static_assert(offsetof(PJRT_Api, PJRT_Event_Destroy) == 80, "PJRT_Api.PJRT_Event_Destroy offset drift");
_Static_assert(offsetof(PJRT_Api, PJRT_Event_IsReady) == 88, "PJRT_Api.PJRT_Event_IsReady offset drift");
_Static_assert(offsetof(PJRT_Api, PJRT_Event_Error) == 96, "PJRT_Api.PJRT_Event_Error offset drift");
_Static_assert(offsetof(PJRT_Api, PJRT_Event_Await) == 104, "PJRT_Api.PJRT_Event_Await offset drift");
_Static_assert(offsetof(PJRT_Api, PJRT_Event_OnReady) == 112, "PJRT_Api.PJRT_Event_OnReady offset drift");
_Static_assert(offsetof(PJRT_Api, PJRT_Client_Create) == 120, "PJRT_Api.PJRT_Client_Create offset drift");
_Static_assert(offsetof(PJRT_Api, PJRT_Client_Destroy) == 128, "PJRT_Api.PJRT_Client_Destroy offset drift");
_Static_assert(offsetof(PJRT_Api, PJRT_Client_PlatformName) == 136, "PJRT_Api.PJRT_Client_PlatformName offset drift");
_Static_assert(offsetof(PJRT_Api, PJRT_Client_ProcessIndex) == 144, "PJRT_Api.PJRT_Client_ProcessIndex offset drift");
_Static_assert(offsetof(PJRT_Api, PJRT_Client_PlatformVersion) == 152, "PJRT_Api.PJRT_Client_PlatformVersion offset drift");
_Static_assert(offsetof(PJRT_Api, PJRT_Client_Devices) == 160, "PJRT_Api.PJRT_Client_Devices offset drift");
_Static_assert(offsetof(PJRT_Api, PJRT_Client_AddressableDevices) == 168, "PJRT_Api.PJRT_Client_AddressableDevices offset drift");
_Static_assert(offsetof(PJRT_Api, PJRT_Client_LookupDevice) == 176, "PJRT_Api.PJRT_Client_LookupDevice offset drift");
_Static_assert(offsetof(PJRT_Api, PJRT_Client_LookupAddressableDevice) == 184, "PJRT_Api.PJRT_Client_LookupAddressableDevice offset drift");
_Static_assert(offsetof(PJRT_Api, PJRT_Client_AddressableMemories) == 192, "PJRT_Api.PJRT_Client_AddressableMemories offset drift");
_Static_assert(offsetof(PJRT_Api, PJRT_Client_Compile) == 200, "PJRT_Api.PJRT_Client_Compile offset drift");
_Static_assert(offsetof(PJRT_Api, PJRT_Client_DefaultDeviceAssignment) == 208, "PJRT_Api.PJRT_Client_DefaultDeviceAssignment offset drift");
_Static_assert(offsetof(PJRT_Api, PJRT_Client_BufferFromHostBuffer) == 216, "PJRT_Api.PJRT_Client_BufferFromHostBuffer offset drift");
_Static_assert(offsetof(PJRT_Api, PJRT_DeviceDescription_Id) == 224, "PJRT_Api.PJRT_DeviceDescription_Id offset drift");
_Static_assert(offsetof(PJRT_Api, PJRT_DeviceDescription_ProcessIndex) == 232, "PJRT_Api.PJRT_DeviceDescription_ProcessIndex offset drift");
_Static_assert(offsetof(PJRT_Api, PJRT_DeviceDescription_Attributes) == 240, "PJRT_Api.PJRT_DeviceDescription_Attributes offset drift");
_Static_assert(offsetof(PJRT_Api, PJRT_DeviceDescription_Kind) == 248, "PJRT_Api.PJRT_DeviceDescription_Kind offset drift");
_Static_assert(offsetof(PJRT_Api, PJRT_DeviceDescription_DebugString) == 256, "PJRT_Api.PJRT_DeviceDescription_DebugString offset drift");
_Static_assert(offsetof(PJRT_Api, PJRT_DeviceDescription_ToString) == 264, "PJRT_Api.PJRT_DeviceDescription_ToString offset drift");
_Static_assert(offsetof(PJRT_Api, PJRT_Device_GetDescription) == 272, "PJRT_Api.PJRT_Device_GetDescription offset drift");
_Static_assert(offsetof(PJRT_Api, PJRT_Device_IsAddressable) == 280, "PJRT_Api.PJRT_Device_IsAddressable offset drift");
_Static_assert(offsetof(PJRT_Api, PJRT_Device_LocalHardwareId) == 288, "PJRT_Api.PJRT_Device_LocalHardwareId offset drift");
_Static_assert(offsetof(PJRT_Api, PJRT_Device_AddressableMemories) == 296, "PJRT_Api.PJRT_Device_AddressableMemories offset drift");
_Static_assert(offsetof(PJRT_Api, PJRT_Device_DefaultMemory) == 304, "PJRT_Api.PJRT_Device_DefaultMemory offset drift");
_Static_assert(offsetof(PJRT_Api, PJRT_Device_MemoryStats) == 312, "PJRT_Api.PJRT_Device_MemoryStats offset drift");
_Static_assert(offsetof(PJRT_Api, PJRT_Memory_Id) == 320, "PJRT_Api.PJRT_Memory_Id offset drift");
_Static_assert(offsetof(PJRT_Api, PJRT_Memory_Kind) == 328, "PJRT_Api.PJRT_Memory_Kind offset drift");
_Static_assert(offsetof(PJRT_Api, PJRT_Memory_DebugString) == 336, "PJRT_Api.PJRT_Memory_DebugString offset drift");
_Static_assert(offsetof(PJRT_Api, PJRT_Memory_ToString) == 344, "PJRT_Api.PJRT_Memory_ToString offset drift");
_Static_assert(offsetof(PJRT_Api, PJRT_Memory_AddressableByDevices) == 352, "PJRT_Api.PJRT_Memory_AddressableByDevices offset drift");
_Static_assert(offsetof(PJRT_Api, PJRT_Executable_Destroy) == 360, "PJRT_Api.PJRT_Executable_Destroy offset drift");
_Static_assert(offsetof(PJRT_Api, PJRT_Executable_Name) == 368, "PJRT_Api.PJRT_Executable_Name offset drift");
_Static_assert(offsetof(PJRT_Api, PJRT_Executable_NumReplicas) == 376, "PJRT_Api.PJRT_Executable_NumReplicas offset drift");
_Static_assert(offsetof(PJRT_Api, PJRT_Executable_NumPartitions) == 384, "PJRT_Api.PJRT_Executable_NumPartitions offset drift");
_Static_assert(offsetof(PJRT_Api, PJRT_Executable_NumOutputs) == 392, "PJRT_Api.PJRT_Executable_NumOutputs offset drift");
_Static_assert(offsetof(PJRT_Api, PJRT_Executable_SizeOfGeneratedCodeInBytes) == 400, "PJRT_Api.PJRT_Executable_SizeOfGeneratedCodeInBytes offset drift");
_Static_assert(offsetof(PJRT_Api, PJRT_Executable_GetCostAnalysis) == 408, "PJRT_Api.PJRT_Executable_GetCostAnalysis offset drift");
_Static_assert(offsetof(PJRT_Api, PJRT_Executable_OutputMemoryKinds) == 416, "PJRT_Api.PJRT_Executable_OutputMemoryKinds offset drift");
_Static_assert(offsetof(PJRT_Api, PJRT_Executable_OptimizedProgram) == 424, "PJRT_Api.PJRT_Executable_OptimizedProgram offset drift");
_Static_assert(offsetof(PJRT_Api, PJRT_Executable_Serialize) == 432, "PJRT_Api.PJRT_Executable_Serialize offset drift");
_Static_assert(offsetof(PJRT_Api, PJRT_LoadedExecutable_Destroy) == 440, "PJRT_Api.PJRT_LoadedExecutable_Destroy offset drift");
_Static_assert(offsetof(PJRT_Api, PJRT_LoadedExecutable_GetExecutable) == 448, "PJRT_Api.PJRT_LoadedExecutable_GetExecutable offset drift");
_Static_assert(offsetof(PJRT_Api, PJRT_LoadedExecutable_AddressableDevices) == 456, "PJRT_Api.PJRT_LoadedExecutable_AddressableDevices offset drift");
_Static_assert(offsetof(PJRT_Api, PJRT_LoadedExecutable_Delete) == 464, "PJRT_Api.PJRT_LoadedExecutable_Delete offset drift");
_Static_assert(offsetof(PJRT_Api, PJRT_LoadedExecutable_IsDeleted) == 472, "PJRT_Api.PJRT_LoadedExecutable_IsDeleted offset drift");
_Static_assert(offsetof(PJRT_Api, PJRT_LoadedExecutable_Execute) == 480, "PJRT_Api.PJRT_LoadedExecutable_Execute offset drift");
_Static_assert(offsetof(PJRT_Api, PJRT_Executable_DeserializeAndLoad) == 488, "PJRT_Api.PJRT_Executable_DeserializeAndLoad offset drift");
_Static_assert(offsetof(PJRT_Api, PJRT_LoadedExecutable_Fingerprint) == 496, "PJRT_Api.PJRT_LoadedExecutable_Fingerprint offset drift");
_Static_assert(offsetof(PJRT_Api, PJRT_Buffer_Destroy) == 504, "PJRT_Api.PJRT_Buffer_Destroy offset drift");
_Static_assert(offsetof(PJRT_Api, PJRT_Buffer_ElementType) == 512, "PJRT_Api.PJRT_Buffer_ElementType offset drift");
_Static_assert(offsetof(PJRT_Api, PJRT_Buffer_Dimensions) == 520, "PJRT_Api.PJRT_Buffer_Dimensions offset drift");
_Static_assert(offsetof(PJRT_Api, PJRT_Buffer_UnpaddedDimensions) == 528, "PJRT_Api.PJRT_Buffer_UnpaddedDimensions offset drift");
_Static_assert(offsetof(PJRT_Api, PJRT_Buffer_DynamicDimensionIndices) == 536, "PJRT_Api.PJRT_Buffer_DynamicDimensionIndices offset drift");
_Static_assert(offsetof(PJRT_Api, PJRT_Buffer_GetMemoryLayout) == 544, "PJRT_Api.PJRT_Buffer_GetMemoryLayout offset drift");
_Static_assert(offsetof(PJRT_Api, PJRT_Buffer_OnDeviceSizeInBytes) == 552, "PJRT_Api.PJRT_Buffer_OnDeviceSizeInBytes offset drift");
_Static_assert(offsetof(PJRT_Api, PJRT_Buffer_Device) == 560, "PJRT_Api.PJRT_Buffer_Device offset drift");
_Static_assert(offsetof(PJRT_Api, PJRT_Buffer_Memory) == 568, "PJRT_Api.PJRT_Buffer_Memory offset drift");
_Static_assert(offsetof(PJRT_Api, PJRT_Buffer_Delete) == 576, "PJRT_Api.PJRT_Buffer_Delete offset drift");
_Static_assert(offsetof(PJRT_Api, PJRT_Buffer_IsDeleted) == 584, "PJRT_Api.PJRT_Buffer_IsDeleted offset drift");
_Static_assert(offsetof(PJRT_Api, PJRT_Buffer_CopyToDevice) == 592, "PJRT_Api.PJRT_Buffer_CopyToDevice offset drift");
_Static_assert(offsetof(PJRT_Api, PJRT_Buffer_ToHostBuffer) == 600, "PJRT_Api.PJRT_Buffer_ToHostBuffer offset drift");
_Static_assert(offsetof(PJRT_Api, PJRT_Buffer_IsOnCpu) == 608, "PJRT_Api.PJRT_Buffer_IsOnCpu offset drift");
_Static_assert(offsetof(PJRT_Api, PJRT_Buffer_ReadyEvent) == 616, "PJRT_Api.PJRT_Buffer_ReadyEvent offset drift");
_Static_assert(offsetof(PJRT_Api, PJRT_Buffer_UnsafePointer) == 624, "PJRT_Api.PJRT_Buffer_UnsafePointer offset drift");
_Static_assert(offsetof(PJRT_Api, PJRT_Buffer_IncreaseExternalReferenceCount) == 632, "PJRT_Api.PJRT_Buffer_IncreaseExternalReferenceCount offset drift");
_Static_assert(offsetof(PJRT_Api, PJRT_Buffer_DecreaseExternalReferenceCount) == 640, "PJRT_Api.PJRT_Buffer_DecreaseExternalReferenceCount offset drift");
_Static_assert(offsetof(PJRT_Api, PJRT_Buffer_OpaqueDeviceMemoryDataPointer) == 648, "PJRT_Api.PJRT_Buffer_OpaqueDeviceMemoryDataPointer offset drift");
_Static_assert(offsetof(PJRT_Api, PJRT_CopyToDeviceStream_Destroy) == 656, "PJRT_Api.PJRT_CopyToDeviceStream_Destroy offset drift");
_Static_assert(offsetof(PJRT_Api, PJRT_CopyToDeviceStream_AddChunk) == 664, "PJRT_Api.PJRT_CopyToDeviceStream_AddChunk offset drift");
_Static_assert(offsetof(PJRT_Api, PJRT_CopyToDeviceStream_TotalBytes) == 672, "PJRT_Api.PJRT_CopyToDeviceStream_TotalBytes offset drift");
_Static_assert(offsetof(PJRT_Api, PJRT_CopyToDeviceStream_GranuleSize) == 680, "PJRT_Api.PJRT_CopyToDeviceStream_GranuleSize offset drift");
_Static_assert(offsetof(PJRT_Api, PJRT_CopyToDeviceStream_CurrentBytes) == 688, "PJRT_Api.PJRT_CopyToDeviceStream_CurrentBytes offset drift");
_Static_assert(offsetof(PJRT_Api, PJRT_TopologyDescription_Create) == 696, "PJRT_Api.PJRT_TopologyDescription_Create offset drift");
_Static_assert(offsetof(PJRT_Api, PJRT_TopologyDescription_Destroy) == 704, "PJRT_Api.PJRT_TopologyDescription_Destroy offset drift");
_Static_assert(offsetof(PJRT_Api, PJRT_TopologyDescription_PlatformName) == 712, "PJRT_Api.PJRT_TopologyDescription_PlatformName offset drift");
_Static_assert(offsetof(PJRT_Api, PJRT_TopologyDescription_PlatformVersion) == 720, "PJRT_Api.PJRT_TopologyDescription_PlatformVersion offset drift");
_Static_assert(offsetof(PJRT_Api, PJRT_TopologyDescription_GetDeviceDescriptions) == 728, "PJRT_Api.PJRT_TopologyDescription_GetDeviceDescriptions offset drift");
_Static_assert(offsetof(PJRT_Api, PJRT_TopologyDescription_Serialize) == 736, "PJRT_Api.PJRT_TopologyDescription_Serialize offset drift");
_Static_assert(offsetof(PJRT_Api, PJRT_TopologyDescription_Attributes) == 744, "PJRT_Api.PJRT_TopologyDescription_Attributes offset drift");
_Static_assert(offsetof(PJRT_Api, PJRT_Compile) == 752, "PJRT_Api.PJRT_Compile offset drift");
_Static_assert(offsetof(PJRT_Api, PJRT_Executable_OutputElementTypes) == 760, "PJRT_Api.PJRT_Executable_OutputElementTypes offset drift");
_Static_assert(offsetof(PJRT_Api, PJRT_Executable_OutputDimensions) == 768, "PJRT_Api.PJRT_Executable_OutputDimensions offset drift");
_Static_assert(offsetof(PJRT_Api, PJRT_Buffer_CopyToMemory) == 776, "PJRT_Api.PJRT_Buffer_CopyToMemory offset drift");
_Static_assert(offsetof(PJRT_Api, PJRT_Client_CreateViewOfDeviceBuffer) == 784, "PJRT_Api.PJRT_Client_CreateViewOfDeviceBuffer offset drift");
_Static_assert(offsetof(PJRT_Api, PJRT_Executable_Fingerprint) == 792, "PJRT_Api.PJRT_Executable_Fingerprint offset drift");
_Static_assert(offsetof(PJRT_Api, PJRT_Client_TopologyDescription) == 800, "PJRT_Api.PJRT_Client_TopologyDescription offset drift");
_Static_assert(offsetof(PJRT_Api, PJRT_Executable_GetCompiledMemoryStats) == 808, "PJRT_Api.PJRT_Executable_GetCompiledMemoryStats offset drift");
_Static_assert(offsetof(PJRT_Api, PJRT_Memory_Kind_Id) == 816, "PJRT_Api.PJRT_Memory_Kind_Id offset drift");
_Static_assert(offsetof(PJRT_Api, PJRT_ExecuteContext_Create) == 824, "PJRT_Api.PJRT_ExecuteContext_Create offset drift");
_Static_assert(offsetof(PJRT_Api, PJRT_ExecuteContext_Destroy) == 832, "PJRT_Api.PJRT_ExecuteContext_Destroy offset drift");
_Static_assert(offsetof(PJRT_Api, PJRT_Buffer_CopyRawToHost) == 840, "PJRT_Api.PJRT_Buffer_CopyRawToHost offset drift");
_Static_assert(offsetof(PJRT_Api, PJRT_AsyncHostToDeviceTransferManager_Destroy) == 848, "PJRT_Api.PJRT_AsyncHostToDeviceTransferManager_Destroy offset drift");
_Static_assert(offsetof(PJRT_Api, PJRT_AsyncHostToDeviceTransferManager_TransferData) == 856, "PJRT_Api.PJRT_AsyncHostToDeviceTransferManager_TransferData offset drift");
_Static_assert(offsetof(PJRT_Api, PJRT_Client_CreateBuffersForAsyncHostToDevice) == 864, "PJRT_Api.PJRT_Client_CreateBuffersForAsyncHostToDevice offset drift");
_Static_assert(offsetof(PJRT_Api, PJRT_AsyncHostToDeviceTransferManager_RetrieveBuffer) == 872, "PJRT_Api.PJRT_AsyncHostToDeviceTransferManager_RetrieveBuffer offset drift");
_Static_assert(offsetof(PJRT_Api, PJRT_AsyncHostToDeviceTransferManager_Device) == 880, "PJRT_Api.PJRT_AsyncHostToDeviceTransferManager_Device offset drift");
_Static_assert(offsetof(PJRT_Api, PJRT_AsyncHostToDeviceTransferManager_BufferCount) == 888, "PJRT_Api.PJRT_AsyncHostToDeviceTransferManager_BufferCount offset drift");
_Static_assert(offsetof(PJRT_Api, PJRT_AsyncHostToDeviceTransferManager_BufferSize) == 896, "PJRT_Api.PJRT_AsyncHostToDeviceTransferManager_BufferSize offset drift");
_Static_assert(offsetof(PJRT_Api, PJRT_AsyncHostToDeviceTransferManager_SetBufferError) == 904, "PJRT_Api.PJRT_AsyncHostToDeviceTransferManager_SetBufferError offset drift");
_Static_assert(offsetof(PJRT_Api, PJRT_AsyncHostToDeviceTransferManager_AddMetadata) == 912, "PJRT_Api.PJRT_AsyncHostToDeviceTransferManager_AddMetadata offset drift");
_Static_assert(offsetof(PJRT_Api, PJRT_Client_DmaMap) == 920, "PJRT_Api.PJRT_Client_DmaMap offset drift");
_Static_assert(offsetof(PJRT_Api, PJRT_Client_DmaUnmap) == 928, "PJRT_Api.PJRT_Client_DmaUnmap offset drift");
_Static_assert(offsetof(PJRT_Api, PJRT_Client_CreateUninitializedBuffer) == 936, "PJRT_Api.PJRT_Client_CreateUninitializedBuffer offset drift");
_Static_assert(offsetof(PJRT_Api, PJRT_Client_UpdateGlobalProcessInfo) == 944, "PJRT_Api.PJRT_Client_UpdateGlobalProcessInfo offset drift");
_Static_assert(offsetof(PJRT_Api, PJRT_TopologyDescription_Deserialize) == 952, "PJRT_Api.PJRT_TopologyDescription_Deserialize offset drift");
_Static_assert(offsetof(PJRT_Api, PJRT_Client_CreateAliasBuffer) == 960, "PJRT_Api.PJRT_Client_CreateAliasBuffer offset drift");
_Static_assert(offsetof(PJRT_Api, PJRT_Client_FulfillAliasBuffer) == 968, "PJRT_Api.PJRT_Client_FulfillAliasBuffer offset drift");
_Static_assert(offsetof(PJRT_Api, PJRT_LoadedExecutable_GetDeviceAssignment) == 976, "PJRT_Api.PJRT_LoadedExecutable_GetDeviceAssignment offset drift");
_Static_assert(PJRT_Buffer_Type_PRED == 1, "PJRT_Buffer_Type_PRED drift");
_Static_assert(PJRT_Buffer_Type_S8 == 2, "PJRT_Buffer_Type_S8 drift");
_Static_assert(PJRT_Buffer_Type_S16 == 3, "PJRT_Buffer_Type_S16 drift");
_Static_assert(PJRT_Buffer_Type_S32 == 4, "PJRT_Buffer_Type_S32 drift");
_Static_assert(PJRT_Buffer_Type_S64 == 5, "PJRT_Buffer_Type_S64 drift");
_Static_assert(PJRT_Buffer_Type_U8 == 6, "PJRT_Buffer_Type_U8 drift");
_Static_assert(PJRT_Buffer_Type_U16 == 7, "PJRT_Buffer_Type_U16 drift");
_Static_assert(PJRT_Buffer_Type_U32 == 8, "PJRT_Buffer_Type_U32 drift");
_Static_assert(PJRT_Buffer_Type_U64 == 9, "PJRT_Buffer_Type_U64 drift");
_Static_assert(PJRT_Buffer_Type_F16 == 10, "PJRT_Buffer_Type_F16 drift");
_Static_assert(PJRT_Buffer_Type_F32 == 11, "PJRT_Buffer_Type_F32 drift");
_Static_assert(PJRT_Buffer_Type_F64 == 12, "PJRT_Buffer_Type_F64 drift");
_Static_assert(PJRT_Buffer_Type_BF16 == 13, "PJRT_Buffer_Type_BF16 drift");
_Static_assert(PJRT_Buffer_Type_C64 == 14, "PJRT_Buffer_Type_C64 drift");
_Static_assert(PJRT_Buffer_Type_C128 == 15, "PJRT_Buffer_Type_C128 drift");
#endif
