module NL = Lax_numpy
module UF = Ufuncs
module RED = Reductions
module IDX = Indexing

let all ?axis ?keepdims x = RED.all ?axis ?keepdims x
let any ?axis ?keepdims x = RED.any ?axis ?keepdims x
let sum ?axis ?keepdims x = RED.sum ?axis ?keepdims x
let prod ?axis ?keepdims x = RED.prod ?axis ?keepdims x
let max ?axis ?keepdims x = RED.max ?axis ?keepdims x
let min ?axis ?keepdims x = RED.min ?axis ?keepdims x
let mean ?axis ?keepdims x = RED.mean ?axis ?keepdims x
let var ?axis ?keepdims ?ddof x = RED.var ?axis ?keepdims ?ddof x
let std ?axis ?keepdims ?ddof x = RED.std ?axis ?keepdims ?ddof x
let ptp ?axis ?keepdims x = RED.ptp ?axis ?keepdims x
let cumsum ?axis x = RED.cumsum ?axis x
let cumprod ?axis x = RED.cumprod ?axis x
let argmax ?axis ?keepdims x = NL.argmax ?axis ?keepdims x
let argmin ?axis ?keepdims x = NL.argmin ?axis ?keepdims x
let astype x dtype = NL.astype x dtype
let clip ?min ?max x = NL.clip ?min ?max x
let round ?decimals x = NL.round ?decimals x
let copy x = NL.copy x
let conj x = UF.conj x
let conjugate x = UF.conjugate x
let reshape x shape = NL.reshape x shape
let ravel x = NL.ravel x
let flatten x = NL.ravel x
let transpose ?axes x = NL.transpose ?axes x
let squeeze ?axis x = NL.squeeze ?axis x
let swapaxes axis1 axis2 x = NL.swapaxes axis1 axis2 x
let repeat ?axis x repeats = NL.repeat ?axis x repeats
let diagonal ?offset ?axis1 ?axis2 x = NL.diagonal ?offset ?axis1 ?axis2 x

let trace ?offset ?axis1 ?axis2 ?dtype x =
  NL.trace ?offset ?axis1 ?axis2 ?dtype x

let searchsorted ?side x v = NL.searchsorted ?side x v
let take ?axis ?mode x indices = IDX.take ?axis ?mode x indices
let t x = NL.transpose x
let mt x = NL.matrix_transpose x
let real x = UF.real x
let imag x = UF.imag x
let neg x = UF.negative x
let pos x = UF.positive x
let abs x = UF.abs x
let invert x = UF.invert x
let eq a b = UF.equal a b
let ne a b = UF.not_equal a b
let lt a b = UF.less a b
let le a b = UF.less_equal a b
let gt a b = UF.greater a b
let ge a b = UF.greater_equal a b
let add a b = UF.add a b
let sub a b = UF.subtract a b
let mul a b = UF.multiply a b
let truediv a b = UF.true_divide a b
let floordiv a b = UF.floor_divide a b
let mod_ a b = UF.mod_ a b
let pow a b = UF.power a b
let and_ a b = UF.bitwise_and a b
let or_ a b = UF.bitwise_or a b
let xor a b = UF.bitwise_xor a b
let lshift a b = UF.left_shift a b
let rshift a b = UF.right_shift a b
